name: cinestatapp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_auth: ^4.16.0
  #firebase: ^9.0.3
  firebase_core: ^4.1.1
  firebase_data_connect: ^0.2.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/img.png
    - assets/images/Captura_de_tela_2025-10-08_195021.png
