query ReadAllUsers @auth(level: USER){
  users {
    userId
    userName
    userEmail
    userCreatedAt
  }
}

query ReadSingleUser($id: UUID!) @auth(level: USER) {
  user(id : $id) {
    userId
    userName
    userEmail
    userCreatedAt
  }
}
query ReadManagerUnits ($managerId: UUID!) @auth(level: USER){
  units (where: { unitManager: { id: { eq: $managerId } } }) {
    unitName
    unitLocal
    unitMacCapacity
    unitManager {
      userName
    }
    unitActive
  }
}

query ReadAllMovies @auth(level: USER) {
  movie {
    id
    movieTitle
    movieGenre
    movieAgeClass
    movieDuration
    movieDistrib
    movieFormat
    movieDirector
    movieActive
  }
}





