// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgN-st7T7eutjtM1W4mCsI_H4wnKjF92Q',
    appId: '1:798752324745:web:419b7c0e9338e755c61a58',
    messagingSenderId: '798752324745',
    projectId: 'cinestat-384ba',
    authDomain: 'cinestat-384ba.firebaseapp.com',
    storageBucket: 'cinestat-384ba.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgN-st7T7eutjtM1W4mCsI_H4wnKjF92Q',
    appId: '1:798752324745:android:419b7c0e9338e755c61a58',
    messagingSenderId: '798752324745',
    projectId: 'cinestat-384ba',
    storageBucket: 'cinestat-384ba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgN-st7T7eutjtM1W4mCsI_H4wnKjF92Q',
    appId: '1:798752324745:ios:419b7c0e9338e755c61a58',
    messagingSenderId: '798752324745',
    projectId: 'cinestat-384ba',
    storageBucket: 'cinestat-384ba.firebasestorage.app',
    iosBundleId: 'com.example.cinestatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgN-st7T7eutjtM1W4mCsI_H4wnKjF92Q',
    appId: '1:798752324745:ios:419b7c0e9338e755c61a58',
    messagingSenderId: '798752324745',
    projectId: 'cinestat-384ba',
    storageBucket: 'cinestat-384ba.firebasestorage.app',
    iosBundleId: 'com.example.cinestatapp',
  );
}
